### PR TITLE
Issue/32 open file

### LINKED ISSUE #32: Opening a model file without opening the project folder causes unintuitive error
According to the spec this passes `rootPath=None` to the `initialize` call. This causes the server to raise the following exception:
"chdir: path should be string, bytes, os.PathLike or integer, not NoneType". The `initialize` method should be updated to check for `rootPath=None` and raise an exception that makes clear to the user that an inmanta configuration file only has meaning within the context of an inmanta project.

### PR DESCRIPTION
**Pull request by arnaudsjs**
Closes #32

### CODE REVIEW

File: src/extension.ts [hunk 1]
```diff
@@ -16,7 +16,12 @@ export async function activate(context: ExtensionContext) {
 	let lsOutputChannel = null;
 
 	async function startServerAndClient() {
-		const clientOptions = await getClientOptions();
+		var clientOptions;
```
Comment (andraskvr) [inline src/extension.ts:19]:
```suggestion
		let clientOptions;
```

File: src/extension.ts [hunk 2]
```diff
@@ -25,10 +30,18 @@ export async function activate(context: ExtensionContext) {
 	}
 
 	async function getClientOptions(): Promise<LanguageClientOptions> {
+		var compilerVenv: string = workspace.getConfiguration('inmanta').compilerVenv;
+		if (!compilerVenv) {
+			if(context.storageUri == undefined){
+				window.showWarningMessage("A folder should be opened instead of a file in order to use the inmanta extension.");
+				throw "A folder should be opened instead of a file in order to use the inmanta extension.";
```
Comment (andraskvr) [inline src/extension.ts:37]:
```suggestion
				throw Error("A folder should be opened instead of a file in order to use the inmanta extension.");
```

File: src/extension.ts [hunk 3]
```diff
@@ -25,10 +30,18 @@ export async function activate(context: ExtensionContext) {
 	}
 
 	async function getClientOptions(): Promise<LanguageClientOptions> {
+		var compilerVenv: string = workspace.getConfiguration('inmanta').compilerVenv;
```
Comment (andraskvr) [inline src/extension.ts:33]:
```suggestion
		let compilerVenv: string = workspace.getConfiguration('inmanta').compilerVenv;
```

File: src/test/suite/loadExtension.test.ts [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+import * as path from 'path';
+
+import { Uri, window, commands, workspace, TextDocument, TextEditor, extensions } from 'vscode';
+
+const cfFile: Uri = Uri.file(path.resolve(__dirname, '../../../src/test/workspace/valid.cf'));
+
+describe('Load extension', () => {
+
+    beforeEach(async function() {
+        // await commands.executeCommand('workbench.action.closeWorkspace');
```
Comment (andraskvr) [inline src/test/suite/loadExtension.test.ts:12]: Comment leftover

**Review by andraskvr — CHANGES_REQUESTED** [review]

**Review by andraskvr — APPROVED** [review]

File: server/src/inmantals/pipeserver.py [hunk 5]
```diff
@@ -38,12 +38,12 @@ def main():
     stdin = PipeIOStream(sys.stdin.fileno())
     stdout = PipeIOStream(sys.stdout.fileno())
     handler = InmantaLSHandler(stdin, stdout, "0.0.0.0")
-    sys.stderr.write("starting")
+    sys.stderr.write("starting\n")
```
Comment (sanderr) [inline server/src/inmantals/pipeserver.py:41]: Write these to stdout instead? The client now logs stdout as well.

**Review by sanderr — CHANGES_REQUESTED** [review]

File: server/src/inmantals/pipeserver.py (hunk 5 above)
Comment (andraskvr) [reply server/src/inmantals/pipeserver.py]: I think that's only true for the `tcpserver`

Comment (sanderr) [reply server/src/inmantals/pipeserver.py]: Right, nevermind then.

**Review by sanderr — APPROVED** [review]
